### PR TITLE
JSON Schema SERDE

### PR DESCRIPTION
**Pull request by kidpollo**
# Checklist

- [x] tests
- [x] updated [CHANGELOG](../CHANGELOG.md) (the "unreleased" section)

### CODE REVIEW

**Comment by kidpollo** [comment]
Still working through issues with top level Array types. The deserializer does not like them :(

**Comment by kidpollo** [comment]
@99-not-out  @gphilipp Would love your input on this pr so far 

👋🏽  btw, how are things going?

**Comment by kidpollo** [comment]
Should handle top level arrays now

**Comment by gphilipp** [comment]
Hi @kidpollo Hope everything is well for you 👋. Would you mind renaming the commits (get rid of `wip-`)?

**Review by gphilipp — DISMISSED** [review]

**Comment by kidpollo** [comment]
Ok now i' sure this works on kstreams topologies :P

**Pull request merged**
