### PR TITLE
[Fix] correctly clojurize deeply nested JSON

### PR DESCRIPTION
**Pull request by kidpollo**
JSON _SR Serde wasn't correctly clojurizing deeply nested maps
# Checklist

- [x] tests
- [x] updated [CHANGELOG](../CHANGELOG.md) (the "unreleased" section)

### CODE REVIEW

**Comment by kidpollo** [comment]
Ping @gphilipp any chance you can look at this?

**Comment by kidpollo** [comment]
ping @mattford63 ??

**Comment by gphilipp** [comment]
> Ping @gphilipp any chance you can look at this?

I’m sorry Paco, I wish I had time to work on this but I’ve left FC and I don’t do Clojure at all at the moment 😞

**Comment by kidpollo** [comment]
@99-not-out Ping! :D Maybe we need to open up the list of contributors?

**Review by 99-not-out — APPROVED** [review]

**Pull request merged**
