### PR TITLE
Upgrade to Kafka 2.4.1

### PR DESCRIPTION
**Pull request by csenol**
# Checklist

- [x] tests
- [ ] updated [CHANGELOG](../CHANGELOG.md) (the "unreleased" section)

### CODE REVIEW

**Comment by csenol** [comment]
Kafka 2.4 is providing new partition assignment strategies such as cooperative-sticky
It would be good if jackdaw can catch-up

**Comment by cddr** [comment]
Might be worth also updating the images used by CI to the corresponding confluent release.

https://github.com/FundingCircle/jackdaw/blob/master/.circleci/config.yml#L44

**Review by cddr — APPROVED** [review]
lgtm

**Comment by csenol** [comment]
Thanks for the review.
When are you planning to have a release?

**Comment by cddr** [comment]
I'm no longer an administrator so dunno when someone will be able to get a release out. If you have a pressing need though, you may be able to just override the kafka dependencies in your own project.clj.

**Comment by mt3593** [comment]
Any update on this, any administrators able to get a release out?

**Comment by robert-pierce** [comment]
Following ... we could use the new support for `Named` class. We are producing graph images of our topologies as a method of documentation, and naming the nodes would be extremely helpful.

**Comment by dakra** [comment]
fyi, I have merged a few PRs that I needed (including this one) in [my fork](https://github.com/dakra/jackdaw).
I also published it [to clojars](https://clojars.org/dakra/jackdaw).

I don't really want to maintain this fork or make something official
or anything. I just did it because I needed it personally, maybe it
helps you too until @FundingCircle picks development up again.

**Comment by gphilipp** [comment]
Closing since we upgraded to 2.8.0 via #292

**Pull request closed without merging**
